//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public Nullable<System.DateTime> StartFrom { get; set; }
        public Nullable<System.DateTime> EndTo { get; set; }
        public long HealthCareProviderId { get; set; }
        public Nullable<long> PatientId { get; set; }
        public Nullable<bool> NoShow { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<long> UserIdEntered { get; set; }
    
        public virtual HealthCareProvider HealthCareProvider { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
