//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long NoteId { get; set; }
        public long HealthCareProviderId { get; set; }
        public long PatientId { get; set; }
        public string Note1 { get; set; }
        public Nullable<long> NoteTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<long> UserIdEntered { get; set; }
    
        public virtual HealthCareProvider HealthCareProvider { get; set; }
        public virtual NoteType NoteType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
